### ISSUE TITLE
Button Missing for the "Sharing the Light" Bonus Events

### ISSUE THREAD

**Issue by F-Lambda** [p3lim-wow/ExtraQuestButton#105] opened 2024-09-22 07:33 UTC
The quest items for [Sharing the Light](https://www.wowhead.com/achievement=40311/sharing-the-light) events are missing. These are the events that appear after igniting the larger keyflames in the Spreading the Light quest area.

The [Sentry Flare](https://www.wowhead.com/item=211073/sentry-flare) (211073) is used for these 3 quests:

- [Bleak Sand](https://www.wowhead.com/quest=79471/bleak-sand) (79471)
- [The Midnight Sentry](https://www.wowhead.com/quest=78657/the-midnight-sentry) (78657)
- [Waters of War](https://www.wowhead.com/quest=79470/waters-of-war) (79470)

The [Dirt-Cracker Pick](https://www.wowhead.com/item=215467/dirt-cracker-pick) (215467) is used for just 1 quest:

- [Lurking Below](https://www.wowhead.com/quest=79469/lurking-below) (79469)

**Comment by p3lim** [comment] 2024-09-22 08:47
Duplicate of https://github.com/p3lim-wow/ExtraQuestButton/issues/104

**Closed by p3lim** 2024-09-22 08:47 UTC
Labels: bug
