### ISSUE TITLE
Support world quest 79960

### ISSUE THREAD

**Issue by Gnarfoz** [p3lim-wow/ExtraQuestButton#100] opened 2024-09-06 22:11 UTC
**Describe the solution you'd like**
Show the button for the world quest https://www.wowhead.com/quest=79960/taking-it-to-go

**Describe alternatives you've considered**
Clicking the quest tracker like a barbarian.

**Comment by p3lim** [comment] 2024-09-06 23:19
Duplicate of #98.

**Closed by p3lim** 2024-09-06 23:19 UTC
Labels: enhancement
